### ISSUE TITLE
Add manifest.json with most recent python-miio version

### ISSUE THREAD

**Issue by TriptonPt** [syssi/xiaomi_cooker#13]
Have been trying to understand why my hassio restarts took over 5mins and I narrowed it down to this component !

Every time I am restarting the python-miio command runs twice (before server shuts down and when it's starting), and this adds alone about 3mins to the restart time of my instance !

/usr/local/bin/python3 -m pip install python-miio==0.4.7 --no-cache-dir --upgrade --constraint /usr/src/homeassistant/homeassistant/package_constraints.txt --find-links https://wheels.home-assistant.io/alpine-3.10/armv7/ --prefer-binary

Isn't there a way to integrate this component without having to go through the python-miio upgrade routine every time? Otherwise my only option will be moving this to a second HA instance to offload the restart delay .

Thanks

**Comment by syssi** [comment]
Fixed.

**Comment by TriptonPt** [comment]
That was ridiculously simple :) Ty
