### ISSUE TITLE
How to use start / stop ?

### ISSUE THREAD

**Issue by Titanius** [syssi/xiaomi_cooker#18]
I have add all Sensors to the Lovelace UI
![D201005B-5CE4-4D77-9056-15DB4FCC4514](https://user-images.githubusercontent.com/22440498/77853263-90dae180-71e3-11ea-8cb5-0f55acbf33a3.jpeg)

How i can use Start / Stop in my Lovelace too and choose the 3 Taste options Soft, Moderate, Rigid.

IH Rice Cooker

Soft:
soft and delicous
Fluffy , delicious , exquisite and sweet
Hardness: 33%
weich und lecker
Flauschig, lecker, exquisit und süß

Moderate
glutinous and delicious
Fragrant , sweet , glossy and delicious
Hardness: 66%
klebrig und lecker
Duftend, süß, glänzend und lecker

Rigid
chewy and flexible
Full , pleasant and chewy rice grains
Hardness: 99%
zäh und flexibel
Volle, angenehme und zähe Reiskörner

**Comment by syssi** [comment]
Did you find a solution? Just call the `xiaomi_miio_cooker.start` service with a proper `profile`.

**Comment by Titanius** [comment]
Thank you. I try it. Do you have an example yaml of this device?

**Comment by syssi** [comment]
I've extended the README of the project by two examples: https://github.com/syssi/xiaomi_cooker
