### ISSUE TITLE
Add Support Xiaomi Water Purifier C1 yunmi.waterpuri.lx11

### ISSUE THREAD

**Issue by anhnvme** [syssi/xiaomi_cooker#27]
Hello,

I don't know how can i contact with u, so i'm open this issue. ( Sorry ).
But can you write a new custom components for this Device ?
I see at latest python-miio support this device, but i don't know how to write a complete custom_component. for Home Assisstant

Thanks you so much

**Comment by dollop80** [comment]
Take a look at the relevant component https://github.com/dollop80/homeassistant-xiaomi-water-purifier-yunmi
You may close the issue ;-)

**Comment by syssi** [comment]
@dollop80 Good job! Do you like to contribute to `python-miio` to support your device?

**Comment by dollop80** [comment]
@syssi, thank you. Sure, I'll be happy to contribute

**Comment by syssi** [comment]
Let's close this issue because there is a custom component available which handles the devices already.
