### ISSUE TITLE
Add chunmi.cooker.eh1 support

### ISSUE THREAD

**Issue by minskmail** [syssi/xiaomi_cooker#28]
Please, add chunmi.cooker.eh1 support

**Comment by bachulator** [comment]
Having same issue. Ready provide input and supprt development.


`Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_cooker/issues and provide the following data: chunmi.cooker.eh1`

**Comment by minskmail** [comment]
I'm already connect it via anorher integration.

**Comment by bachulator** [comment]
Hi @minskmail. Mind to share how did you achieve this?

**Comment by minskmail** [comment]
https://github.com/al-one/hass-xiaomi-miot

**Comment by bachulator** [comment]
Hi @minskmail. Well, I have played a bit, but all I get to control  the cooker are two entities (switch and sensor). Is it sane for you?

**Comment by minskmail** [comment]
> Hi @minskmail. Well, I have played a bit, but all I get to control the cooker are two entities (switch and sensor). Is it sane for you?

Actually no, but thats better than nothing.  Can I ask you what kind of info or controls you want to have in HA for the cooker?

**Comment by bachulator** [comment]
Indeed it is, but still less than this integration originally provides. Well, for starters, it will be handy to choose which mode the cooker is operating. Then I guess timer how long current mode stays active. Then some less essential stuff, like temperature sensor etc. 

Ok it seems folks are working with the issue and hopefully @syssi will come up with update:
https://github.com/syssi/xiaomi_cooker/issues/3

**Comment by ranrinc** [comment]
> Would be possible to integrate from this forked repository: https://github.com/sschirr/xiaomi_cooker. I try to use it, but I have problems with official HA Xiaomi Miio integration.
> 
> thx.

Hi, would like to add your integrations since I have chunmi.cooker.eh1

Now how do I installed it? Which branch are the one that support chunmi.cooker.eh1

Will need to do it manually and hope yours code is working. Thanks

**Comment by FaserF** [comment]
Develop branch is the correct one that’s working

**Comment by ranrinc** [comment]
Heem.. adding this integrations and unsure what happen.. but the integrations did not appear at all

**Comment by FaserF** [comment]
Just follow the instructions after adding the addon. This this work for me. Let us know if you are having any troubles

**Comment by syssi** [comment]
Duplicate #3.
