### ISSUE TITLE
Please fit for Xiaomi YLIH02CM IH 1S 3L chunmi.cooker.k1pro1

### ISSUE THREAD

**Issue by tieppm** [syssi/xiaomi_cooker#30]
i have Xiaomi YLIH02CM IH 1S 3L chunmi.cooker.k1pro1
i user your component but it it does not get data from the rice cooker
please fit it
thank you vermuch
sr. my English very bad

![New Bitmap Image (2)](https://user-images.githubusercontent.com/42457105/106387722-ad503780-640d-11eb-8787-f1c46821d9f0.jpg)

**Comment by syssi** [comment]
Duplicate #46.

**Comment by syssi** [comment]
Duplicate #11.
