### ISSUE TITLE
MI Rice Cooker error in KeepWarm

### ISSUE THREAD

**Issue by pauligbrest** [syssi/xiaomi_cooker#4]
019-02-09 14:28:02 ERROR (MainThread) [custom_components.sensor.xiaomi_cooker] Exception in async_update_callback when dispatching 'xiaomi_cooker_updated': ('192.168.88.14',)

Traceback (most recent call last):

  File "/config/custom_components/sensor/xiaomi_cooker.py", line 98, in async_update_callback

    temperature_history is not None:

IndexError: pop from empty list

**Comment by syssi** [comment]
Please update this component and try again. :-)

**Comment by ktpx** [comment]
I'm getting the same issue.

**Comment by pauligbrest** [comment]
> Please update this component and try again. :-)

I update this component. But the same issue

**Comment by ktpx** [comment]
The update was only to restructure the files into the new tree layout in homeassistant.  Nothing that would fix this bug.

**Comment by ktpx** [comment]
changing the code in sensor.py to (line 98+)

                        temperature_history.temperature:
                                self._state = temperature_history.temperatures.pop()

Fixes the error thrown, but still does not get the temp during keepwarm.  Looks like it gets the temp from the homeassistant history, and maybe this is too slow and fails ..

**Comment by ktpx** [comment]
Changing the code to: 

                if self._attr == 'temperature' and \
                        state.mode in [OperationMode.Running, OperationMode.AutoKeepWarm] and \
                        temperature_history.temperatures:   
                                self._state = temperature_history.temperatures.pop()

clears the error, but no temperature is shown still.  I think it might not get the temp history from the cooker during autowarm?
