### ISSUE TITLE
Add chunmi.ihcooker.exp1 support 

### ISSUE THREAD

**Issue by gfzmake** [syssi/xiaomi_cooker#40]
I have a Mi induction cooker 
Model: DCL01CM 
model: chunmi.ihcooker.exp1
2100W 
220-240V
Year 2019

Here is the error:

Logger: custom_components.xiaomi_miio_cooker
Source: custom_components/xiaomi_miio_cooker/__init__.py:132
Integration: xiaomi_miio_cooker (documentation, issues)
First occurred: 10:30:15 a. m. (1 occurrences)
Last logged: 10:30:15 a. m.
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_cooker/issues and provide the following data: chunmi.ihcooker.exp1

Thanks

**Comment by syssi** [comment]
Duplicate #26
