### ISSUE TITLE
Add chunmi.cooker.k1pro1 support

### ISSUE THREAD

**Issue by tieppm** [syssi/xiaomi_cooker#46]
Name: Mijia Pressure IH Rice Cooker 1S 3L 
Model: chunmi.cooker.k1pro1
Model no: YLIH02CM 
Link: https://home.mi.com/webapp/content/baike/product/index.html?model=chunmi.cooker.k1pro1#/
link: https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Acooker%3A0000A00B%3Achunmi-k1pro1%3A1
image:
![111037879-a844c600-8458-11eb-91df-704588f4bfb8](https://user-images.githubusercontent.com/42457105/147810503-4d648718-3c86-4e48-bea5-401a2cc4ed09.png)
![111037969-0b365d00-8459-11eb-8f9c-61cde53f24e8](https://user-images.githubusercontent.com/42457105/147810506-885399f3-e273-4fcc-b585-41ee35693366.jpg)

**Comment by syssi** [comment]
Duplicate #11.
