### ISSUE TITLE
Not working after 0.88

### ISSUE THREAD

**Issue by ktpx** [syssi/xiaomi_cooker#5]
After 0.88 this component doesnt work anymore.  Homeassistant also suggests adding the component/sensor under its own folder (../custom_components/xiaomi_cooker/sensor.py.  

2019-02-25 11:29:26 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.xiaomi_cooker.sensor. Make sure all dependencies are installed
ImportError: No module named 'custom_components.xiaomi_cooker.sensor'; 'custom_components.xiaomi_cooker' is not a package

Link to similar case:  

https://community.home-assistant.io/t/custom-component-roon-not-working-in-0-88/100591/2

**Comment by ktpx** [comment]
So this needs to be changed to 
custom_components/xiaomi_cooker/sensor.py
custom_components/xiaomi_cooker/__init__.py

**Comment by syssi** [comment]
Thanks for your PR! https://github.com/syssi/xiaomi_cooker/pull/6

**Comment by ktpx** [comment]
> Thanks for your PR! #6

You're welcome :D
