### ISSUE TITLE
How to find exact model of Rice Cooker

### ISSUE THREAD

**Issue by B48D81EFCC** [syssi/xiaomi_cooker#50]
Hi,

I am wondering how I can I find out the exact model of my rice cooker.
The hostname / DNS of my device is: ESP-CE01F0

The Xiaomi Home App just say: Mi IH Rice Cooker.

**Comment by syssi** [comment]
Nice to see you here too. ;-) You could ask the MiHome Cloud about the model names, IPs and tokens of your devices:

https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

As soon you now the IP and the token of your rice cooker you could use the `miiocli` command line tool from `python-miio` to ask your device directly:

```
$ pip3 install python-miio
$ ~/.local/bin/miiocli device --ip XXX --token YYY info
```

**Comment by syssi** [comment]
In this case you are lucky and this custom component should work for you!
