### ISSUE TITLE
ERROR  YLIH02CM IH 1S 3L chunmi.cooker.k1pro1

### ISSUE THREAD

**Issue by tieppm** [syssi/xiaomi_cooker#53]
Thank you for your support YLIH02CM chunmi.cooker.k1pro1
But after I configure according to the instructions, there is an error message in the log as shown.
I don't know where I misconfigured
I have tried with model: chunmi.cooker.normal5, model: chunmi.cooker.k1pro1, model: chunmi.cooker.normal2 all error.
Please help, thanks!
![image](https://user-images.githubusercontent.com/42457105/192179019-d5df340f-1eaf-4712-8ff4-2c5413077613.png)
![image](https://user-images.githubusercontent.com/42457105/192179170-fd22e7e3-6ec7-430c-8190-841110dd6c81.png)

**Comment by syssi** [comment]
I've closed this weekend some duplicate issues. Your device isn't supported yet!

**Comment by tieppm** [comment]
i'm waiting for you to fix it
