### ISSUE TITLE
Does it need to have internet connection after pairing?

### ISSUE THREAD

**Issue by tajo48** [syssi/xiaomi_cooker#54]

**Comment by syssi** [comment]
These depends on the firmware and your model. Just give it a try by blocking the internet connection. In general the `miIO` communication is local network communication but some firmware doesn't work well (crashs) if you block the internet access and the micloud cannot be reached anymore.

**Comment by tajo48** [comment]
Thanks I will try it.
If it won't work i will try searching for any firmware changer like in mi scooter
Or if [this project](https://codeberg.org/unrelentingtech/micloudfaker) could work.

**Comment by syssi** [comment]
micloudfaker is a good idea. Replacing the firmware is in general an option / possible because most devices are ESP8266 or ESP32 based but I'm not aware of already existing alternative firmware.

**Comment by syssi** [comment]
Please feel free to close this issue if it's solved.

**Comment by syssi** [comment]
73 de DO2KSM ;-)
