### ISSUE TITLE
Unable to find component xiaomi_cooker

### ISSUE THREAD

**Issue by Wooo0** [syssi/xiaomi_cooker#7]
/config/custom_components/xiaomi_cooker/__init__.py
/config/custom_components/xiaomi_cooker/sensor.py

/config/configuration.yaml

xiaomi_cooker:
 name: Xiaomi Rice Cooker
 host: ***
 token: ****
 model: chunmi.cooker.normal2

**Comment by syssi** [comment]
Please use HACS to install this custom component!
