### ISSUE TITLE
Unable to find services.yaml for the xiaomi_cooker integration

### ISSUE THREAD

**Issue by pauligbrest** [syssi/xiaomi_cooker#8]
Unable to find services.yaml for the xiaomi_cooker integration
Home assistant 0.92

**Comment by TriptonPt** [comment]
Have the same Error in Hassio 0.102

**Comment by Gio76** [comment]
Same issue in **Home Assistant 0.109.0**

![image](https://user-images.githubusercontent.com/26906928/80672339-a1c68d80-8ad6-11ea-9131-7d7d3fbdb9a7.png)

**Comment by gaasehengger** [comment]
I just installed the component and have the exact same problem. I was unable to find any hint as to how to resolve it. 
Is there a solution? 
Since there has been no reaction whatsoever: Is this project still active?

**Comment by syssi** [comment]
The custom component provides a `services.yaml` since version 0.2.1.
