### ISSUE TITLE
Compatability with custom_component updater 

### ISSUE THREAD

**Issue by bachulator** [syssi/xiaomi_cooker#9]
Recently awesome people in home assistant community have created a very useful tool to automate follow up on custom components https://github.com/custom-components/custom_updater

In order to make it work the maintainer of repo should add json file to repo for change tracking. Example:
https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

Would be coll to have similar feature for the component. Thanks!

**Comment by drndos** [comment]
custom_updater is deprecated, should intergate to https://hacs.xyz/

**Comment by syssi** [comment]
Please use HACS to install this custom component!
